Fix after using new MD

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1,10 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 VERSION=0.1
 PACKAGE=paintdotnet
 prefix=/usr/local
 config=DEBUG_ANY_CPU
 configurations=" DEBUG_ANY_CPU RELEASE_ANY_CPU RELEASE_AND_PACKAGE_ANY_CPU"
-required_packages=""
+common_packages=""
+
 
 usage ()
 {
@@ -31,56 +32,64 @@ validate_config ()
 	return 0
 }
 
+check_package ()
+{
+	name=`echo $1 | cut -d\; -f1`
+	version=`echo $1 | cut -d\; -f2`
+
+	echo -n "Checking for package '$name'.." | tee -a config.log
+	pkg-config --atleast-version=$version $name
+	if [ $? -ne 0 ]; then
+		echo " ERROR: Package named '$name' >= $version not found." | tee -a config.log
+		echo "Try adjusting your PKG_CONFIG_PATH environment variable." | tee -a config.log
+		return 1
+	fi
+	echo " found." | tee -a config.log
+}
+
 check_required_packages ()
 {
 	echo "Looking for required packages" | tee config.log
-	for pkg in $required_packages; do
-		name=`echo $pkg | cut -d\; -f1`
-		version=`echo $pkg | cut -d\; -f2`
-
-		echo -n "Checking for package '$name'.." | tee -a config.log
-		pkg-config --atleast-version=$version $name
-		if [ $? -ne 0 ]; then
-			echo " ERROR: Package named '$name' >= $version not found." | tee -a config.log
-			echo "Try adjusting your PKG_CONFIG_PATH environment variable." | tee -a config.log
-			return 1
-		fi
-		echo " found." | tee -a config.log
+	var=required_packages_$config
+	for pkg in $common_packages ${!var}; do
+		check_package $pkg
+		retval=$?
+		[ $retval -ne 0 ] && return $retval
 	done
 	return 0
 }
 
 while test x$1 != x; do
-        case $1 in
-                --prefix=*)
-                        prefix=`echo $1 | sed 's/--prefix=//'`
-                        ;;
-                --prefix)
-                        echo --prefix needs an argument: --prefix=directory >&2
-
-                        ;;
+		case $1 in
+		--prefix=*)
+				prefix=`echo $1 | sed 's/--prefix=//'`
+				;;
+		--prefix)
+				shift
+				prefix=$1
+				;;
 		--config=*)
-                        conf=`echo $1 | sed 's/--config=//'`
-			validate_config "$conf"
-			if [ $? -eq 1 ]; then
-				config=$conf
-			else
-				echo "Invalid config name - $conf"
-				usage
-				exit 1
-			fi
-                        ;;
+				conf=`echo $1 | sed 's/--config=//'`
+				validate_config "$conf"
+				if [ $? -eq 1 ]; then
+					config=$conf
+				else
+					echo "Invalid config name - $conf"
+					usage
+					exit 1
+				fi
+                ;;
 		--help)
 			usage
 			exit
 			;;
-                *)
-                        echo Unknown argument $1 >&2
+		*)
+			echo Unknown argument $1 >&2
 			usage
 			exit 1
 			;;
-        esac
-        shift
+		esac
+		shift
 done
 
 check_required_packages
